// Command paircodebook trains the codebook of one of nn/pair.go's tiers and
// writes it to nn/h3g_codebook.go or nn/h4g_codebook.go.
//
// It is Lloyd's algorithm run through the trellis. The start is k-means on a
// unit Gaussian in the plane, one centroid an entry — QTIP's own start for its HYB
// table. Then, round after round, a fresh Gaussian source is coded with the
// current table and every entry moves to the mean of the pairs its states
// coded. A fresh source a round, because a table of 4096 numbers fitted to one
// fixed sample of a few million learns that sample: on a sample of two million
// the training error ran 0.0074 under the held-out one.
//
// The source is Gaussian and not a model's weights on purpose: the rotation
// and the per-block normalisation make every block of every tensor a unit
// Gaussian, and a table fitted to one checkpoint would be a table fitted to
// one checkpoint.
package main

import (
	"flag"
	"fmt"
	"math"
	"math/rand"
	"os"
	"strings"

	"github.com/ThiraSoft/golem/compress"
	"github.com/ThiraSoft/golem/nn"
	"github.com/ThiraSoft/golem/vk"
)

func main() {
	tier := flag.String("tier", "H3G", "H3G or H4G")
	rounds := flag.Int("rounds", 40, "Lloyd rounds through the trellis")
	size := flag.Int("n", 1<<23, "Gaussian weights coded a round")
	entries := flag.Int("entries", 0, "pairs in the table, a power of two; zero is the tier's. Anything else is an experiment and the file it writes is not the tier's")
	out := flag.String("out", "", "where to write the table; nn/<tier>_codebook.go by default")
	flag.Parse()

	q, ok := nn.QuantOf(*tier)
	p := nn.PairTierOf(q)
	if !ok || p == nil {
		fmt.Fprintln(os.Stderr, "paircodebook: -tier is H3G or H4G")
		os.Exit(1)
	}
	o := compress.PairOptsFor(q)
	if *entries != 0 {
		// The entry is the top of s·(s+1)'s sixteen low bits whatever the
		// table's size: a table twice the size reads one more bit below.
		o.Shift -= bits(*entries) - bits(o.Entries)
		o.Entries = *entries
	}
	if *out == "" {
		*out = "nn/" + strings.ToLower(*tier) + "_codebook.go"
	}

	d, err := vk.Open()
	if err != nil {
		fmt.Fprintln(os.Stderr, "h3gcodebook: the card trains this; without one it takes a day:", err)
		os.Exit(1)
	}
	defer d.Close()

	book := kmeans(o.Entries, 1<<18, 30, rand.New(rand.NewSource(1)))
	src := rand.New(rand.NewSource(2))
	held := gaussian(*size, rand.New(rand.NewSource(3)))
	for r := 0; r < *rounds; r++ {
		train := gaussian(*size, src)
		states := make([]uint16, len(train)/2)
		rec := append([]float32(nil), train...)
		enc, err := vk.NewPairEncoder(d, len(rec), book, o.L, o.K, o.Shift)
		if err != nil {
			panic(err)
		}
		if err := enc.QuantizePath(rec, states); err != nil {
			panic(err)
		}
		sum := make([]float64, len(book))
		cnt := make([]float64, len(book)/2)
		for i, s := range states {
			e := o.Entry(s)
			sum[2*e] += float64(train[2*i])
			sum[2*e+1] += float64(train[2*i+1])
			cnt[e]++
		}
		for e := range cnt {
			if cnt[e] > 0 {
				book[2*e] = float32(sum[2*e] / cnt[e])
				book[2*e+1] = float32(sum[2*e+1] / cnt[e])
			}
		}
		// Held out, with the table as a kernel will hold it.
		for i := range book {
			book[i] = nn.HalfToFloat(nn.FloatToHalf(book[i]))
		}
		enc.Close()
		if enc, err = vk.NewPairEncoder(d, len(held), book, o.L, o.K, o.Shift); err != nil {
			panic(err)
		}
		test := append([]float32(nil), held...)
		if err := enc.QuantizePath(test, make([]uint16, len(test)/2)); err != nil {
			panic(err)
		}
		enc.Close()
		var mse float64
		for i, v := range held {
			e := float64(v - test[i])
			mse += e * e
		}
		mse /= float64(len(held))
		fmt.Printf("round %2d  held-out %.6f  %.3f dB\n", r, mse, -10*math.Log10(mse))
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/paircodebook; DO NOT EDIT.\n\npackage nn\n\n")
	name := strings.ToLower(*tier)
	fmt.Fprintf(&b, "// %sCodebookHalf is %s's codebook: %d pairs of half-precision numbers,\n", name, *tier, o.Entries)
	fmt.Fprintf(&b, "// trained by Lloyd's algorithm through the trellis on a unit Gaussian,\n")
	fmt.Fprintf(&b, "// %d rounds of %d weights.\n", *rounds, *size)
	fmt.Fprintf(&b, "var %sCodebookHalf = [2 * %d]uint16{", name, o.Entries)
	for i, v := range book {
		if i%8 == 0 {
			b.WriteString("\n\t")
		} else {
			b.WriteString(" ")
		}
		fmt.Fprintf(&b, "0x%04x,", nn.FloatToHalf(v))
	}
	b.WriteString("\n}\n")
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

func gaussian(n int, r *rand.Rand) []float32 {
	x := make([]float32, n)
	for i := range x {
		x[i] = float32(r.NormFloat64())
	}
	return x
}

// kmeans is Lloyd's algorithm in the plane on a Gaussian sample: the start.
func kmeans(k, n, iters int, r *rand.Rand) []float32 {
	data := gaussian(2*n, r)
	c := make([]float32, 2*k)
	for i := 0; i < k; i++ {
		j := r.Intn(n)
		c[2*i], c[2*i+1] = data[2*j], data[2*j+1]
	}
	asg := make([]int32, n)
	for it := 0; it < iters; it++ {
		compress.Parallel(n, func(lo, hi int) {
			for i := lo; i < hi; i++ {
				best, bj := float32(math.MaxFloat32), 0
				for j := 0; j < k; j++ {
					dx, dy := data[2*i]-c[2*j], data[2*i+1]-c[2*j+1]
					if dd := dx*dx + dy*dy; dd < best {
						best, bj = dd, j
					}
				}
				asg[i] = int32(bj)
			}
		})
		sum := make([]float64, 2*k)
		cnt := make([]float64, k)
		for i, a := range asg {
			sum[2*a] += float64(data[2*i])
			sum[2*a+1] += float64(data[2*i+1])
			cnt[a]++
		}
		for j := 0; j < k; j++ {
			if cnt[j] > 0 {
				c[2*j], c[2*j+1] = float32(sum[2*j]/cnt[j]), float32(sum[2*j+1]/cnt[j])
			}
		}
	}
	return c
}

func bits(n int) int {
	b := 0
	for n > 1 {
		n >>= 1
		b++
	}
	return b
}
